### ISSUE TITLE
Awk lexer

### ISSUE THREAD

**Issue by ghost** [mirror/scite#1]
See here:

http://github.com/zufuliu/notepad2/blob/master/src/EditLexers/stlAwk.c

**Comment by svnpenn** [comment]
https://github.com/mirror/scintilla/issues/1

**Comment by svnpenn** [comment]
https://github.com/simonsteele/pn/issues/152

**Comment by svnpenn** [comment]
https://github.com/Microsoft/vscode/issues/42265

**Comment by svnpenn** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1620
